import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./nav";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "I am vishal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><Script  async src="https://www.googletagmanager.com/gtag/js?id=G-SMJWQN720D"/><Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-SMJWQN720D', {
                page_path: window.location.pathname,
              });
            `,
          }}
        /></head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
